export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  RECOVER: "/recover",
  RECOVER_ACCOUNT: "/recover-account",
  DASHBOARD: "/dashboard",
  STUDY_SETS: "/study-sets",
  STUDY_SETS_DETAIL: "/study-sets/:id",
  NOTES: "/notes",
  NOTES_DETAIL: "/notes/:id",
  FLASHCARDS: "/flashcards",
  FLASHCARDS_DECK: "/flashcards/:id",
  QUIZZES: "/quizzes",
  QUIZZES_DETAIL: "/quizzes/:id",
  UPLOAD: "/upload",
  PROFILE: "/profile",
  AUTH_CLOUD_CALLBACK: "/auth/cloud-callback",
  ACCOUNT_DELETED: "/account-deleted",
  LINK_ACCOUNT: "/link-account",
  CONFIRM_EMAIL_CHANGE: "/confirm-email-change",
  SECURITY_ACTION: "/security-action",
} as const;
