export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  RECOVER: "/recover",
  DASHBOARD: "/dashboard",
  STUDY_SETS: "/study-sets",
  STUDY_SETS_DETAIL: "/study-sets/:id",
  NOTES: "/notes",
  NOTES_DETAIL: "/notes/:id",
  FLASHCARDS: "/flashcards",
  FLASHCARDS_DECK: "/flashcards/:id",
  QUIZZES: "/quizzes",
  QUIZZES_DETAIL: "/quizzes/:id",
  UPLOAD: "/upload",
  PROFILE: "/profile",
} as const;
