name: noteably
services:
  noteably:
    build: .
    container_name: noteably
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application

  celery:
    build: .
    container_name: noteably-celery
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A config worker --loglevel=info
    stop_grace_period: 5s
    init: true

  redis:
    image: redis:7-alpine
    container_name: noteably-redis
    ports:
      - "6379:6379"
