# Generated by Django 4.2.28 on 2026-02-23 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, editable=False)),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('onedrive', 'OneDrive'), ('dropbox', 'Dropbox')], db_index=True, max_length=20)),
                ('_access_token', models.TextField(db_column='access_token')),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token', null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cloud_connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'provider'], name='cloud_conne_user_id_4ec31e_idx')],
                'unique_together': {('user_id', 'provider')},
            },
        ),
    ]
