# Generated by Django 4.2.29 on 2026-03-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudconnection',
            name='provider',
            field=models.CharField(choices=[('google_drive', 'Google Drive'), ('dropbox', 'Dropbox')], db_index=True, max_length=20),
        ),
    ]
