# Generated by Django 4.2.27 on 2026-01-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_quizattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='quiz_attemp_job_id_e242f7_idx',
            old_name='quiz_attempts_job_user_idx',
        ),
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='quiz_attemp_user_id_b856b3_idx',
            old_name='quiz_attempts_user_created_idx',
        ),
    ]
