# Generated by Django 4.2.28 on 2026-02-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_job_celery_task_id'),
        ('generation', '0003_rename_quiz_attempts_job_user_idx_quiz_attemp_job_id_e242f7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='ingestion.job')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='chat_messag_job_id_dd2631_idx')],
            },
        ),
    ]
