# Generated by Django 4.2.27 on 2026-01-31 00:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, help_text='Supabase User UUID')),
                ('name', models.CharField(help_text='Friendly name for the key', max_length=100)),
                ('prefix', models.CharField(db_index=True, help_text='First 8 chars of key for lookup', max_length=8)),
                ('hashed_key', models.CharField(help_text='SHA-256 hash of the secret part', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
