# Generated by Django 4.2.28 on 2026-02-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_id_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
