# Generated by Django 4.2.27 on 2026-01-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_job_transcription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cached_content_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='cached_flashcard_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='cached_quiz_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='cached_summary_preview',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='cached_summary_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
