# Generated by Django 4.2.27 on 2026-01-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_add_cached_content_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('queued', 'Queued'), ('transcribing', 'Transcribing'), ('extracting_text', 'Extracting Text'), ('generating_summary', 'Generating Summary'), ('generating_notes', 'Generating Notes'), ('generating_flashcards', 'Generating Flashcards'), ('generating_quiz', 'Generating Quiz'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=50),
        ),
    ]
