# Generated by Django 4.2.27 on 2026-02-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_update_status_check_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
