# Generated by Django 4.2.28 on 2026-02-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_add_youtube_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('checking_video', 'Checking Video'), ('downloading', 'Downloading'), ('uploading', 'Uploading'), ('queued', 'Queued'), ('transcribing', 'Transcribing'), ('extracting_text', 'Extracting Text'), ('generating_summary', 'Generating Summary'), ('generating_notes', 'Generating Notes'), ('generating_flashcards', 'Generating Flashcards'), ('generating_quiz', 'Generating Quiz'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=50),
        ),
    ]
