# Generated by Django 4.2.28 on 2026-02-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0008_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Optional parameters like summary_length, focus, etc.'),
        ),
    ]
