# Generated by Django 4.2.29 on 2026-03-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0009_alter_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file_type',
            field=models.CharField(max_length=255),
        ),
    ]
